# EDH Comparisons - Config File
# Fill in the values below. Do not add quotes around values.
# Lines starting with # are comments and are ignored.

[archidekt]
# Your Archidekt username
username = joshfoote7@gmail.com

# Your Archidekt password
password = ZR93KHhgPz.c#Z.

